{
 "title": "ProxySQL Instance Summary [TESTComp]",
 "tags": [
  "Percona",
  "MySQL_HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "proxysql",
    "label": "ProxySQL Instance",
    "query": {
     "query": "label_values(proxysql_mysql_status_active_transactions, node_name)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(proxysql_mysql_status_active_transactions, node_name)"
    }
   },
   {
    "name": "hostgroup",
    "label": "Node Namegroup",
    "query": {
     "query": "label_values(proxysql_connection_pool_status{node_name=\"$proxysql\"}, hostgroup)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, instance)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, namespace)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{instance=~\"$instance\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{instance=\"$instance\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "command",
    "label": "Command",
    "query": {
     "query": "label_values(proxysql_mysql_command_counter_latency_milliseconds_bucket{node_name=\"$proxysql\"},command)"
    }
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "ProxySQL Instance Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hostgroup Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "scalar(count(count(proxysql_connection_pool_status{node_name=~\"$proxysql\", hostgroup=~\"$hostgroup\"}) by (hostgroup)))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Client Connections (All Host Groups)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (max_over_time(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[$interval]) or \nmax_over_time(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Client Questions (All Host Groups)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Question Rate"
    }
   ]
  },
  {
   "title": "Active Backend Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) (max_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or\nmax_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Failed Backend Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) (rate(proxysql_connection_pool_conn_err{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_conn_err{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Top 30 Active Frontend Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "topk_max (30, (avg by (node_name,client_host) (max_over_time(proxysql_processlist_client_connection_list{node_name=~\"$proxysql\"}[$interval]) or max_over_time(proxysql_processlist_client_connection_list{node_name=~\"$proxysql\"}[5m]))))",
     "legendFormat": "{{ client_host }}"
    }
   ]
  },
  {
   "title": "Client Frontend Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name,user) (max_over_time(proxysql_processlist_detailed_client_connection_count{node_name=~\"$proxysql\",hostgroup=~\"$hostgroup\"}[$interval]) or max_over_time(proxysql_processlist_detailed_client_connection_count{node_name=~\"$proxysql\",hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Connection Pool Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint Status",
   "type": "table-old",
   "description": "Status number to state mapping:\n\n1 `ONLINE`\n\n2 `SHUNNED`\n\n3 `OFFLINE_SOFT`\n\n4 `OFFLINE_HARD`\n\n5 `SHUNNED_REPLICATION_LAG`\n\nFor status details, see the [description](https://github.com/sysown/proxysql/blob/master/doc/admin_tables.md#mysql_servers).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "avg by (endpoint,hostgroup) (proxysql_runtime_servers_status{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"})",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Connection Status Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Endpoint Statuses - $hostgroup",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "repeat": "hostgroup",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by (endpoint,hostgroup) (proxysql_runtime_servers_status{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"})",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queries Routed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) (rate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Query processor time efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name) ((rate(proxysql_mysql_status_query_processor_time_nsec{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_query_processor_time_nsec{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m])))",
     "legendFormat": "QP_efficiency_query"
    },
    {
     "expr": "avg by (node_name) ((rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m])))",
     "legendFormat": "Questions"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) (max_over_time(proxysql_connection_pool_conn_free{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or max_over_time(proxysql_connection_pool_conn_free{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Endpoints Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) (max_over_time(proxysql_connection_pool_latency_us{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or \nmax_over_time(proxysql_connection_pool_latency_us{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Executed Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_mysql_command_counter_latency_milliseconds_count{node_name=~\"$proxysql\"}[$interval])",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Queries Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_mysql_command_counter_latency_milliseconds_sum{node_name=~\"$proxysql\"}[$interval])",
     "legendFormat": "{{ command }}"
    }
   ]
  },
  {
   "title": "Queries Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(proxysql_mysql_command_counter_latency_milliseconds_bucket{node_name=~\"$proxysql\"}[5m])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Queries Latency Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Commands Latency - $command",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "repeat": "command",
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(proxysql_mysql_command_counter_latency_milliseconds_bucket{command=~\"$command\",node_name=~\"$proxysql\"}[5m])) by (le))",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Cache memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "QC Total Memory used"
    },
    {
     "expr": "avg by (node_name) ((max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[5m]))/\n(max_over_time(proxysql_mysql_status_query_cache_entries{node_name=\"$proxysql\"}[$interval]) or\nmax_over_time(proxysql_mysql_status_query_cache_entries{node_name=\"$proxysql\"}[5m])))",
     "legendFormat": "Bytes for cached query avg"
    }
   ]
  },
  {
   "title": "Query Cache efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name) (((rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m]))))        ",
     "legendFormat": "Query Cache GET efficiency"
    },
    {
     "expr": "avg by (node_name) (((rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m]))))        ",
     "legendFormat": "Insert VS read efficiency (high is good)"
    }
   ]
  },
  {
   "title": "Network Traffic and Mirroring efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "avg by (node_name,endpoint) ((rate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) + rate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval])) or (irate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]) + irate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Mirroring efficiency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_mysql_status_mirror_concurrency{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_mirror_concurrency{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Concurrent Mirror threads"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_mysql_status_mirror_queue_length{node_name=\"$proxysql\"}[$interval]) or \nmax_over_time(proxysql_mysql_status_mirror_queue_length{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Mirror queue length (queries)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"})",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "avg by (node_name) (proxysql_mysql_status_sqlite3_memory_bytes{node_name=\"$proxysql\"})",
     "legendFormat": "SQLite"
    },
    {
     "expr": "avg by (node_name) (proxysql_mysql_status_connpool_memory_bytes{node_name=\"$proxysql\"})",
     "legendFormat": "Connection Pool"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Used by the Authentication module"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Allocated in pages by the Application"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Allocated by the Application"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Extents mapped by the Allocator"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Dedicated to Metadata"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Physically Resident Data pages Mapped by the Allocator"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Retained Memory"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Memory Used to Store Data"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Used by the Embedded SQLite"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Stack Memory for Mysql Threads"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Stack Memory for Admin Threads"
    },
    {
     "expr": "avg by (node_name) (max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[5m]))",
     "legendFormat": "Stack Memory for Cluster Threads"
    }
   ]
  },
  {
   "title": "Node Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "System Uptime",
     "type": "stat",
     "description": "The parameter shows how long a system has been “up” and running without a shut down or restart.",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "avg by (node_name) ((node_time_seconds{node_name=~\"$proxysql\"} - node_boot_time_seconds{node_name=~\"$proxysql\"}) or (time() - node_boot_time_seconds{node_name=~\"$proxysql\"}))"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "stat",
     "description": "The system load is a measurement of the computational work the system is performing. Each running process either using or waiting for CPU resources adds 1 to the load.",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (avg_over_time(node_load1{node_name=~\"$proxysql\"}[$interval]) or avg_over_time(node_load1{node_name=~\"$proxysql\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "stat",
     "description": "RAM (Random Access Memory) is the hardware in a computing device where the operating system, application programs and data in current use are kept so they can be quickly reached by the device's processor.",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$proxysql\"})"
      }
     ]
    },
    {
     "title": "Memory Available",
     "type": "stat",
     "description": "Percent of Memory Available\nNote: on Modern Linux Kernels amount of Memory Available for application is not the same as Free+Cached+Buffers",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) ((node_memory_MemAvailable_bytes{node_name=~\"$proxysql\"} or (node_memory_MemFree_bytes{node_name=~\"$proxysql\"} + node_memory_Buffers_bytes{node_name=~\"$proxysql\"} + node_memory_Cached_bytes{node_name=~\"$proxysql\"})) / node_memory_MemTotal_bytes{node_name=~\"$proxysql\"} * 100)"
      }
     ]
    },
    {
     "title": "Virtual Memory",
     "type": "stat",
     "description": "RAM + SWAP",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (node_memory_MemTotal_bytes{node_name=~\"$proxysql\"}+node_memory_SwapTotal_bytes{node_name=~\"$proxysql\"})"
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "stat",
     "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (node_name) (sum(avg(node_filesystem_size_bytes{node_name=~\"$proxysql\",fstype=~\"(ext.|xfs|vfat|)\"}) without (mountpoint)) without (device,fstype))"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "stat",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 110 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(node_filesystem_free_bytes{node_name=~\"$proxysql\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"}/node_filesystem_size_bytes{node_name=~\"$proxysql\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay|squashfs\"})*100"
      }
     ]
    },
    {
     "title": "Node",
     "type": "text",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 110 },
     "options": {
      "content": "<h5 style='color:#e68a00;font-weight:bold;text-align:center'><a href=\"/graph/d/node-instance-summary/node-summary?var-node_name=$proxysql\" target=\"_blank\">$node_name</a></h5>"
     }
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "description": "The CPU time is measured in clock ticks or seconds. It is useful to measure CPU time as a percentage of the CPU's capacity, which is called the CPU usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by (node_name,mode) (clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$node_name\",mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[$interval]) or avg_over_time(node_cpu_average{node_name=~\"$node_name\", mode!=\"total\", mode!=\"idle\", mode!=\"user\", mode!=\"system\"}[5m]))),100))",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "CPU Saturation and Max Core Usage",
     "type": "timeseries",
     "description": "When a system is running with maximum CPU utilization, the transmitting and receiving threads must all share the available CPU. This will cause data to be queued more frequently to cope with the lack of CPU. CPU Saturation may be measured as the length of a wait queue, or the time spent waiting on the queue.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((avg_over_time(node_procs_running{node_name=~\"$proxysql\"}[$interval])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$proxysql\"})) or (avg_over_time(node_procs_running{node_name=~\"$proxysql\"}[5m])-1) / scalar(count(node_cpu_seconds_total{mode=\"user\", node_name=~\"$proxysql\"})))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "calculatedInterval": "2s",
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu_seconds_total{node_name=~\"$proxysql\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu_seconds_total{node_name=~\"$proxysql\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "timeseries",
     "description": "Disk I/O includes read or write or input/output operations involving a physical disk. It is the speed with which the data transfer takes place between the hard disk drive and RAM.\n\nSwap Activity is memory management that involves swapping sections of memory to and from physical storage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) (rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024)",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "avg by (node_name) ((rate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{node_name=\"$proxysql\"}[5m]) * 1024 ) + (rate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{node_name=\"$proxysql\"}[5m]) * 1024))",
       "legendFormat": "Total"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpin{node_name=\"$proxysql\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "avg by (node_name) (rate(node_vmstat_pswpout{node_name=\"$proxysql\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{node_name=\"$proxysql\"}[5m]) * 4096)",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Network traffic refers to the amount of data moving across a network at a given point in time.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_receive_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[$interval])) or sum(irate(node_network_receive_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[5m])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$proxysql\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_rx{node_name=\"$proxysql\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "calculatedInterval": "2s",
       "expr": "sum(rate(node_network_transmit_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes_total{node_name=\"$proxysql\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{node_name=\"$proxysql\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{node_name=\"$proxysql\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}